// <auto-generated />
using System;
using DoubleMF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoubleMF.Data.Migrations
{
    [DbContext(typeof(DoubleMFDBContext))]
    partial class DoubleMFDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("DoubleMF.Model.AssetManagtComp", b =>
                {
                    b.Property<int>("AMCId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AMCName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("inDate")
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("AMCId");

                    b.ToTable("T_AssetManagtCO");
                });

            modelBuilder.Entity("DoubleMF.Model.MutualFund", b =>
                {
                    b.Property<int>("MutualFundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AMCId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DowbloadEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("inDate")
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("MutualFundCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MutualFundName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.HasKey("MutualFundId");

                    b.HasIndex("AMCId");

                    b.ToTable("T_MutualFund");
                });

            modelBuilder.Entity("DoubleMF.Model.NetAssetValue", b =>
                {
                    b.Property<int>("NetAssetValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MFMutualFundId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OnDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("NetAssetValueId");

                    b.HasIndex("MFMutualFundId");

                    b.ToTable("T_NetAssetValue");
                });

            modelBuilder.Entity("DoubleMF.Model.MutualFund", b =>
                {
                    b.HasOne("DoubleMF.Model.AssetManagtComp", "AMC")
                        .WithMany("MutualFunds")
                        .HasForeignKey("AMCId");
                });

            modelBuilder.Entity("DoubleMF.Model.NetAssetValue", b =>
                {
                    b.HasOne("DoubleMF.Model.MutualFund", "MF")
                        .WithMany("NetAssetValues")
                        .HasForeignKey("MFMutualFundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
